/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Clases.Carrera;
import Clases.Reporte1;

import conexion.Reporte1Conexion;
import conexion.ParticipanteConexion;
import control.control;
import javax.swing.table.TableColumnModel;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class Reporte2_vista extends javax.swing.JFrame {

    
    control con = new control();
    
    int contador = 0;
    ArrayList<Reporte1> lista = new ArrayList<Reporte1>();
    
    Reporte1Conexion reporte_conexion = new Reporte1Conexion();
   // ArrayList<Participante> lista = new ArrayList<Participante>();
    
    
  public Reporte2_vista() {
        initComponents();
        
        con.iniciaVentana(this);
       
        this.setLocationRelativeTo(this);
            this.setSize(1800,1800);
       
        btnsiguiente1.setVisible(false);
        btnanterior.setVisible(false);
         
          
    }

   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        etiquetaTiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nacionalidad_equipo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_km = new javax.swing.JLabel();
        txt_nombre_equipo = new javax.swing.JLabel();
        combo_ano = new javax.swing.JComboBox<>();
        combo_hora = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtnumero_equipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_posicion = new javax.swing.JLabel();
        txt_numero_vuelta = new javax.swing.JLabel();
        etiquetaTiempo1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_conductor = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JLabel();
        txt_nacionalidad_conductor = new javax.swing.JLabel();
        etiquetaTiempo2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombre_automovil = new javax.swing.JLabel();
        txt_motor = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JLabel();
        txt_velocidad_media = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_mejor_vuelta = new javax.swing.JLabel();
        btnanterior = new javax.swing.JButton();
        btnsiguiente1 = new javax.swing.JButton();
        nohay = new javax.swing.JLabel();
        combo_categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 43, 45));

        etiquetaTiempo.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("Datos del Automovil");
        jPanel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 390, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nacionalidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 40));

        txt_nacionalidad_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Kilómetros Recorridos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 250, 40));

        txt_km.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_km, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 200, 40));

        txt_nombre_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 40));

        combo_ano.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1923", "1924", "1925", "1926", "1927", "1928", "1929" }));
        jPanel1.add(combo_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 130, 40));

        combo_hora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01:00:00", "02:00:00", "03:00:00", "04:00:00", "05:00:00", "06:00:00", "07:00:00", "08:00:00", "09:00:00", "10:00:00", "11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00", "22:00:00", "23:00:00", "24:00:00" }));
        jPanel1.add(combo_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 160, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Numero de Equipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 40));

        txtnumero_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtnumero_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Posición:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Número de Vueltas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 40));

        txt_posicion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 200, 40));

        txt_numero_vuelta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_numero_vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 200, 40));

        etiquetaTiempo1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo1.setText("Datos del Equipo");
        jPanel1.add(etiquetaTiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Apellidos:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nacionalidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 160, 40));

        txt_nombre_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 410, 40));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 400, 40));

        txt_nacionalidad_conductor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nacionalidad_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 280, 40));

        etiquetaTiempo2.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo2.setText("Datos del Conductor");
        jPanel1.add(etiquetaTiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 390, 90));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 110, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Motor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 90, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Categoría:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 130, 40));

        txt_nombre_automovil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_nombre_automovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 550, 40));

        txt_motor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 780, 40));

        txt_categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 680, 560, 40));

        txt_velocidad_media.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_velocidad_media, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 260, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Velocidad Media:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 190, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Tiempo de Mejor Vuelta:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, 40));

        txt_mejor_vuelta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_mejor_vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 200, 40));

        btnanterior.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnanterior.setText("Anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 170, 50));

        btnsiguiente1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsiguiente1.setText("Siguiente");
        btnsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, 170, 50));

        nohay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nohay.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(nohay, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 380, 40));

        combo_categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1001 - 1500", "1501 - 2000", "2001 - 3000", "3001 - 5000", "5001 - 8000", "751 - 1100" }));
        jPanel1.add(combo_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Principal ventana = new  Principal();
                   con.activaVentana(ventana, this);  
                   
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            nohay.setText("");
        btnsiguiente1.setVisible(true);
        btnanterior.setVisible(true);
        
       String ano = combo_ano.getSelectedItem().toString();
        
       
       String categoria = combo_categoria.getSelectedItem().toString();
       
       String var = combo_hora.getSelectedItem().toString();
       
       Time tiempo = Time.valueOf(var);
       
        this.lista = reporte_conexion.reporte2(ano, categoria,tiempo);
        
        mostrar();
        
        }catch(Exception e){
            nohay.setText("No hay Registros de esta Busqueda");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        this.contador --;
        btnsiguiente1.setVisible(true);
        try{
        mostrar();
        }catch(Exception e){
           btnanterior.setVisible(false);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente1ActionPerformed
         this.contador ++;
          btnanterior.setVisible(true);
        try{
        mostrar();
        }catch(Exception e){
             btnsiguiente1.setVisible(false);
        }
    }//GEN-LAST:event_btnsiguiente1ActionPerformed

    
    public void mostrar(){
        txt_nombre_equipo.setText(lista.get(contador).getNombre_equipo());
        txtnumero_equipo.setText(Integer.toString(lista.get(contador).getNumero_equipo()));
        txt_nacionalidad_equipo.setText(lista.get(contador).getNacionalidad_equipo());
        
        txt_posicion.setText(Integer.toString(lista.get(contador).getPosicion_actual()));
        txt_km.setText(Long.toString(lista.get(contador).getKm_recorrido()));
        txt_numero_vuelta.setText(Integer.toString(lista.get(contador).getNumero_vuelta()));
        txt_velocidad_media.setText(Integer.toString(lista.get(contador).getVelocidad_media()));
        
        txt_mejor_vuelta.setText(lista.get(contador).getTiempo_mejor_vuelta().toString());
        
        if(lista.get(contador).getSegundo_nombre() != null)
        txt_nombre_conductor.setText(lista.get(contador).getPrimer_nombre()+" "+lista.get(contador).getSegundo_nombre());
        else
             txt_nombre_conductor.setText(lista.get(contador).getPrimer_nombre());
        
        if(lista.get(contador).getSegundo_apellido() != null)
        txt_apellido.setText(lista.get(contador).getPrimer_apellido()+" "+lista.get(contador).getSegundo_apellido());
        else
        txt_apellido.setText(lista.get(contador).getPrimer_apellido());
       
        txt_nacionalidad_conductor.setText(lista.get(contador).getNacionalidad_conductor());
        
        txt_nombre_automovil.setText(lista.get(contador).getNombre_automovil());
        txt_categoria.setText(lista.get(contador).getNombre_categoria());
        txt_motor.setText(lista.get(contador).getNombre_motor_automovil()+" "+lista.get(contador).getCombustion_motor_automovil()+" "+lista.get(contador).getCilindrada_motor_automovil());
    }
 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte2_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte2_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte2_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte2_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte2_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente1;
    private javax.swing.JComboBox<String> combo_ano;
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_hora;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel etiquetaTiempo1;
    private javax.swing.JLabel etiquetaTiempo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nohay;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_categoria;
    private javax.swing.JLabel txt_km;
    private javax.swing.JLabel txt_mejor_vuelta;
    private javax.swing.JLabel txt_motor;
    private javax.swing.JLabel txt_nacionalidad_conductor;
    private javax.swing.JLabel txt_nacionalidad_equipo;
    private javax.swing.JLabel txt_nombre_automovil;
    private javax.swing.JLabel txt_nombre_conductor;
    private javax.swing.JLabel txt_nombre_equipo;
    private javax.swing.JLabel txt_numero_vuelta;
    private javax.swing.JLabel txt_posicion;
    private javax.swing.JLabel txt_velocidad_media;
    private javax.swing.JLabel txtnumero_equipo;
    // End of variables declaration//GEN-END:variables
}
