/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Clases.Carrera;
import Clases.Clima;
import Clases.Participante;
import conexion.CarreraConexion;
import conexion.ParticipanteConexion;
import control.control;
import javax.swing.table.TableColumnModel;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class Simulador extends javax.swing.JFrame {

    
    control con = new control();
    
    
    
    CarreraConexion carrera_conexion = new CarreraConexion();
   // ArrayList<Participante> lista = new ArrayList<Participante>();
    
    
    ArrayList<Carrera> lista = new ArrayList<Carrera>();
    ArrayList<Carrera> lista_posicion_actualizada = new ArrayList<Carrera>();

    public Simulador() {
        initComponents();
        
        con.iniciaVentana(this);
       
        this.setLocationRelativeTo(this);
            this.setSize(1800,1800);
        /*
        EL CRONOMETRO
        */
        
        t = new Timer(10, acciones);
        
        
         
        
        llenarTabla();
        // llenarTablero();
         
          
    }

    
     private Timer t;
    private int h, m, s, cs;
    private ActionListener acciones = new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent ae) {
            ++cs; 
            
            if(cs==100){
                cs = 0;
                ++s;
            }
            if(((s==10) || (s==20) ||(s==30) ||(s==40) ||(s==50) ||(s==60)) && (cs == 0)) 
            {
             Time tiempo = new Time(h,m,s);  
             
                lista = carrera_conexion.calcular_velocidad_posicion(lista,tiempo);
                
            
                
               //ordena los participantes segun sus posiciones
               lista = carrera_conexion.actualizar_posicion(tiempo);
               
               // calcula el clima 
               Clima clima = new Clima();
               clima = carrera_conexion.calcular_clima(1,tiempo);
               clima_out.setText(clima.getClima());
              humedad_out.setText(clima.getHumedad());
              temperatura_out.setText(clima.getTemperatura());
               //--------------------------------------------
               
               String condicion = carrera_conexion.calcular_condicion_auto(lista, tiempo);
               condicion_txt.setText(condicion);
               
                llenarTabla(lista);
            }
          
            if(s==60) 
            { 
            //  carrera_conexion.calcular_clima();
              
             /* clima_out.setText(clima.getClima());
              humedad_out.setText(clima.getHumedad());
              temperatura_out.setText(clima.getTemperatura());*/
                s = 0;
                ++m;
            }
            if(m==60)
            {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
        
    };
    
    private void actualizarLabel() {
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
        etiquetaTiempo.setText(tiempo);
    }
    
    public void llenarTablero(){
        
       
        
        
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnEmpezar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        etiquetaTiempo = new javax.swing.JLabel();
        btnPausa = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        temperatura_out = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clima_out = new javax.swing.JLabel();
        humedad_out = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        condicion_txt = new javax.swing.JTextArea();
        combohora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 43, 45));

        btnEmpezar.setBackground(new java.awt.Color(102, 102, 255));
        btnEmpezar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmpezar.setText("Empezar Carrera");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 170, 40));

        tabla.setBackground(new java.awt.Color(204, 204, 255));
        tabla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipo", "Conductor", "Auto", "Kilometros Recorridos", "Velocidad Media", "Posicion", "Nombre Tramo"
            }
        ));
        tabla.setAlignmentX(2.0F);
        tabla.setAlignmentY(5.0F);
        tabla.setOpaque(false);
        tabla.setRequestFocusEnabled(false);
        tabla.setRowHeight(36);
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1030, 460));

        etiquetaTiempo.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        jPanel1.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 550, 90));

        btnPausa.setBackground(new java.awt.Color(102, 102, 255));
        btnPausa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPausa.setText("Pausar Carrera");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 170, 40));

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Simular horas");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 220, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Temperatura :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, 40));

        temperatura_out.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(temperatura_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Humedad :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Clima :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 40));

        clima_out.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(clima_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, 40));

        humedad_out.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(humedad_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, 40));

        condicion_txt.setColumns(20);
        condicion_txt.setRows(5);
        jScrollPane1.setViewportView(condicion_txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 210, 240));

        combohora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combohora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jPanel1.add(combohora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 490, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Principal ventana = new  Principal();
                   con.activaVentana(ventana, this);  
                   
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        t.start();
        btnEmpezar.setEnabled(false);
        btnEmpezar.setText("Reanudar Carrera");
        btnPausa.setEnabled(true);
        
      
       
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        t.stop();
        btnEmpezar.setEnabled(true);
        btnPausa.setEnabled(false);
    }//GEN-LAST:event_btnPausaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          
         int hora = Integer.parseInt(combohora.getSelectedItem().toString());
        Time tiempo = new Time(h,m,s);  
        
       
        int minuto = 0;
        int segundo = 0;
        
        if(hora == 24){
            minuto = 59;
            segundo = 50;
            hora= 23;
        }
       
          while((tiempo.getHours() != hora) || (tiempo.getMinutes() != minuto) ||(tiempo.getSeconds() != segundo)){
             
              
             tiempo.setSeconds(tiempo.getSeconds()+10);
             
              System.out.println(tiempo);
             
            if((tiempo.getSeconds()==60)|| (tiempo.getSeconds()==10)|| (tiempo.getSeconds()==20)|| 
                    (tiempo.getSeconds()==30)|| (tiempo.getSeconds()==40)|| (tiempo.getSeconds()==50)) 
            { 
                lista = carrera_conexion.calcular_velocidad_posicion(lista,tiempo);
                
            
                
               //ordena los participantes segun sus posiciones
               lista = carrera_conexion.actualizar_posicion(tiempo);
               
               // calcula el clima 
               Clima clima = new Clima();
               clima = carrera_conexion.calcular_clima(1,tiempo);
               clima_out.setText(clima.getClima());
              humedad_out.setText(clima.getHumedad());
              temperatura_out.setText(clima.getTemperatura());
               //--------------------------------------------
               
               String condicion = carrera_conexion.calcular_condicion_auto(lista, tiempo);
               condicion_txt.setText(condicion);
               
                llenarTabla(lista);
               
            }
            if(tiempo.getSeconds()==60){
                 tiempo.setSeconds(0);
                tiempo.setMinutes(tiempo.getMinutes()+1);
            }
            if(tiempo.getMinutes()==60)
            {
                tiempo.setMinutes(0);
                tiempo.setHours(tiempo.getHours()+1);
            }
           
        }
          
       
    }//GEN-LAST:event_jButton9ActionPerformed

 
    
     private void llenarTabla(){
    
         try{
             
             this.lista = carrera_conexion.traerCorredores();
           
          
         
            
        String[] columna = { "Equipo","Conductor","Auto","Numero de Vuelta","km.Recorridos","Velociad Media","Posicion","Nombre Tramo"};
            DefaultTableModel dtm = new DefaultTableModel(null,columna);
           //ArrayList<Venta> Lista= datosVenta.todosLasVentas();
            int posicion = 1;
         
       //  if(!lista.isEmpty())   {
          for (Carrera est : lista) {
                  
                    String[] row = {Integer.toString(est.getNumero_equipo()),est.getPrimer_nombre()+" "+est.getPrimer_apellido(),
                    est.getNombre_automovil(), Integer.toString(est.getNumero_vuelta()),
                    Long.toString(est.getKm_recorrido())+"M",Integer.toString(est.getVelocidad_media()),Integer.toString(posicion),
                    est.getNombre_pista()};
                 dtm.addRow(row);
                 posicion ++;
          }
               
                  
               tabla.setModel(dtm);
        
            
         
             TableColumnModel columnModel = tabla.getColumnModel();
             
               columnModel.getColumn(0).setPreferredWidth(15);
                columnModel.getColumn(1).setPreferredWidth(150);
                columnModel.getColumn(2).setPreferredWidth(150);
                 columnModel.getColumn(3).setPreferredWidth(20);
                  columnModel.getColumn(4).setPreferredWidth(100);
                  columnModel.getColumn(5).setPreferredWidth(20);
                  columnModel.getColumn(6).setPreferredWidth(15);
                  columnModel.getColumn(7).setPreferredWidth(55);
    }catch(Exception e){
             System.out.println("ocurrio un error en tabla");
    }

    }
     
     
     
     /* public void ordenar(ArrayList<Carrera> lista){
        
         Carrera carrera = new Carrera();
                  
       lista = con.ordenarAlfabeticamente(lista);
        
         
         
          for (Inventario est : lista)
            {
                  datosInventario.agregar(est);
             
                
            }
    }*/
    
    private void llenarTabla(ArrayList<Carrera> lista){
    
         try{
            
            
        String[] columna = { "Equipo","Conductor","Auto","Numero de Vuelta","km.Recorridos","Velociad Media","Posicion","Nombre Tramo"};
            DefaultTableModel dtm = new DefaultTableModel(null,columna);
          
           
       //  if(!lista.isEmpty())   {
          for (Carrera est : lista) {
                  
                    String[] row = {Integer.toString(est.getNumero_equipo()),est.getPrimer_nombre()+" "+est.getPrimer_apellido(),
                    est.getNombre_automovil(),Integer.toString(est.getNumero_vuelta()),
                    Long.toString(est.getKm_recorrido())+" Metros",Integer.toString(est.getVelocidad_media()),Integer.toString(est.getPosicion_actual()),
                    est.getNombre_pista()};
                 dtm.addRow(row);
                 
          }
               
                  
               tabla.setModel(dtm);
               
       TableColumnModel columnModel = tabla.getColumnModel();
             
                columnModel.getColumn(0).setPreferredWidth(15);
                columnModel.getColumn(1).setPreferredWidth(150);
                columnModel.getColumn(2).setPreferredWidth(150);
                 columnModel.getColumn(3).setPreferredWidth(20);
                  columnModel.getColumn(4).setPreferredWidth(100);
                  columnModel.getColumn(5).setPreferredWidth(20);
                  columnModel.getColumn(6).setPreferredWidth(15);
                  columnModel.getColumn(7).setPreferredWidth(55);
    }catch(Exception e){
             System.out.println("ocurrio un error en tabla");
    }

    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnPausa;
    private javax.swing.JLabel clima_out;
    private javax.swing.JComboBox<String> combohora;
    private javax.swing.JTextArea condicion_txt;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel humedad_out;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel temperatura_out;
    // End of variables declaration//GEN-END:variables
}
